name: BasicPlugin
version: '${project.version}'
main: me.oliver193.basicplugin.BasicPlugin
api-version: '1.21'
authors: [ oliver193 ]
website: github.com/oliver194/BasicPlugin
commands:
  heal:
    permission: basicplugin.heal
    description: Heal yourself.
    usage: /<command>
  feed:
    permission: basicplugin.feed
    description: Feed yourself.
    usage: /<command>
  fly:
    permission: basicplugin.fly
    description: Enable or disable flight!
    usage: /<command>
  starve:
    permission: basicplugin.starve
    description: Make yourself starve.
    usage: /<command>
  serverinfo:
    permission: basicplugin.serverinfo
    description: View basic information about the server.
    usage: /<command>